### ISSUE TITLE
Temperature dropdown only shows one value

### ISSUE THREAD

**Issue by beecreate** [jneilliii/OctoPrint-ConsolidatedTabs#6]
Both the Bed and the Hotend temperature dropdowns seem to drop behind a whitespace.
I have 3 values, theres only room to show the first

see: 

![image](https://user-images.githubusercontent.com/62603552/89632299-414ba700-d8a2-11ea-88e8-92b59077bce3.png)

**Comment by jneilliii** [comment]
Thanks, I'll look into this. Probably just needs a little CSS magic to allow overflow.

**Comment by rorosaurus** [comment]
I can confirm this issue, and it appears even if the temperature window is tall enough.

**Comment by jneilliii** [comment]
I've made some updates to the plugin in a separate branch, that should resolve this. If you want to try it out uninstall the current version and install using the URL below in plugin manager > Get More > ...from URL. I also enabled a selecting option that allows you to select a panel to bring it to the front. Only the selected tab is resizable. 

```
https://github.com/jneilliii/OctoPrint-ConsolidatedTabs/archive/0.0.8.zip
```

Also, just as general feedback, what are your thoughts on removing the draggable capability all together and just make the panels sizable? All the panels would then just flow in the order they are in the plugin's settings, wrapping once they go beyond the tab container.

**Comment by jneilliii** [comment]
Oh, this new version changes the logic for the width too, and there's a new setting for either leaving it default width or making it full width of the browser.

**Comment by beecreate** [comment]
Thanks for your quick reply.

At first i thought it didnt work, however after re-reading your instructions, I figured out i had to select the tab first and THEN i can see the resize. (You can click the cross and drag the tab without first selecting it).
It works great, however, i would suggest adding those instructions in the plugin tab.

The 'use browser width' is perfect. that was the only thing i used Themefy for, so i can remove that pluging.

The general feedback question; sounds like a nice idea, but personally i dont have a need for it. (but i'm more of telling the computer what i want, not letting the computer decide what it thinks i want', especially with layout ;) )

It would be great if you could add a 'freeze' that would keep the current setting (scaling/ position / z-order) unless you 'unfreeze'.
Because currently it can happen that you drag something unintended. (but you're free to call this issue closed and just let me create a new feature request for it)

**Comment by jneilliii** [comment]
Yes, the freezing option is something that I intend to add for sure. Thanks for the feedback. I did add the note to the readme, and I will probably add a link to those notes in the plugin's settings as well prior to official release of this version.

**Comment by Jarren141** [comment]
Can confirm that this update fixed the issue. Thanks for sharing the great work!!!

**Comment by rorosaurus** [comment]
I love it! I have some feedback:

1. I think beecreate mentioned this already, but just to recap: If you directly click on the temp dropdown, while some other tab (like Terminal) was selected, this bug reproduces. You must first select the "Temperature" tab, then the dropdown, in order to see the dropdown.

2. If GCode Viewer is in your consolidated tab, and you selected to use the full width, there's a small useless horizontal scroll bar in your browser. (Or mine, at least!)

3. When dragging the tab around, and often when letting go, my browser becomes "busy" (cursor changes to hourglass and locks up for a few seconds). I don't remember this in the previous version.

4. You can't reposition the bottommost tab further downward. I personally wanted to add just a bit of padding between each tab, but it breaks when I get to the last one. :)

5. I'd be fine removing the dragging capability. I think I'd prefer it uses the order from settings, like you suggested, but I understand other users might want to customize it more. But there's definitely something to be said about trying to simplify the scope of the plugin, before it becomes a full-blown window manager! 😅

**Comment by jneilliii** [comment]
> 1. I think beecreate mentioned this already, but just to recap: If you directly click on the temp dropdown, while some other tab (like Terminal) was selected, this bug reproduces. You must first select the "Temperature" tab, then the dropdown, in order to see the dropdown.

This was the best I could do for now. I think I can adjust the selectable option I pushed an update for last night to maybe auto select the panel when you click the drop down. 

> 2. If GCode Viewer is in your consolidated tab, and you selected to use the full width, there's a small useless horizontal scroll bar in your browser. (Or mine, at least!)

That's part of the viewer I think, the scroll bar is the layer height indicator. 

> 3. When dragging the tab around, and often when letting go, my browser becomes "busy" (cursor changes to hourglass and locks up for a few seconds). I don't remember this in the previous version.

It wasn't in the previous version. It was added to indicate that a change is saving after dragging/ resizing. 

> 4. You can't reposition the bottommost tab further downward. I personally wanted to add just a bit of padding between each tab, but it breaks when I get to the last one. :)

Looks like I inadvertently removed the resizer in the tab container last night. I'll put that back in.

> 5. I'd be fine removing the dragging capability. I think I'd prefer it uses the order from settings, like you suggested, but I understand other users might want to customize it more. But there's definitely something to be said about trying to simplify the scope of the plugin, before it becomes a full-blown window manager! 😅

Still on the fence about this.

**Comment by jneilliii** [comment]
I just pushed updates to the 0.0.8 branch that requires activating a panel using shift+click for enabling dragging/resizing. This update also allows for clicking on panels to bring them to the front, which will allow for seeing temperature menus if they extend beyond the boundary of the panel. This is just a minor change to the version you installed @rorosaurus I believe, switching from holding the shift key down instead of the ctrl key.  This resolved some weirdness with certain events where a previously selected tab couldn't be activated.

I looked into adding an option to the selectable to select the temperature panel when a button was clicked (that's what the menu is) and unfortunately, it killed the menu altogether and it wouldn't open. I'll have to loo into other methods of handling that weirdness of having to select the panel first.

**Comment by miobx** [comment]
The issue of the temp drop down staying behind a tab below the temp tab still exists for me.  using 0.0.8
![image](https://user-images.githubusercontent.com/69801061/90399379-dbf97200-e068-11ea-85ae-0a9dc94e760b.png)

**Comment by jneilliii** [comment]
Click on a white area next to the drop down in that panel to being it to the front.

**Comment by miobx** [comment]
I tried your suggestion and it still displays behind the panel below the temp tab

**Comment by jneilliii** [comment]
Can you try this. Click 1 and then click 2.

![image](https://user-images.githubusercontent.com/5249455/90418508-3273aa00-e083-11ea-8a88-286a641679b6.png)

**Comment by miobx** [comment]
Still the same thing......
![image](https://user-images.githubusercontent.com/69801061/90420047-6c45b000-e085-11ea-9301-e58dae3d9fc4.png)

I am using Chrome Browser Version 84.0.4147.105 (Official Build) (64-bit) if that helps.

**Comment by miobx** [comment]
OK wait........If I open the drop down then click on white space after the drop down is open it comes to the front.    If that was the direction above I missed the sequence......

**Comment by jneilliii** [comment]
Ok, that was not what I was expecting, but I can see now why that might be the case. There's something about the click events that get blocked on certain items and not on others as part of the jQuery selectable library. That must be at play here. Glad you got a temporary workaround until I can figure out how to select that panel when the menu opens up.

**Comment by jneilliii** [comment]
So with recent development of my gridstack implementation the drop downs cause the panel to become scrollable, which allows you to get to all the items. I feel that's a fair compromise. If you want to test it out you can copy/paste the URL below into Plugin Manager > Get More > ...from URL and clicking install. Once installed you'll need to re-add your tabs and arrange the way you like.

```
https://github.com/jneilliii/OctoPrint-ConsolidatedTabs/archive/develop/gridstack.zip
```
